#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

if [[ "$DOCKER_REPO" = *"rlworkgroup/grage-headless" ]]; then
  echo "Building target garage-dev-18.04"
  docker build \
		-f "$DOCKERFILE_PATH" \
		--target garage-dev-18.04 \
		-t "$IMAGE_NAME" \
		.
elif [[ "$DOCKER_REPO" = *"rlworkgroup/garage-nvidia" ]]; then
  echo "Building target garage-nvidia-18.04"
  docker build \
		-f "$DOCKERFILE_PATH" \
		--target garage-nvidia-18.04 \
		-t "$IMAGE_NAME" \
		--build-arg PARENT_IMAGE="nvidia/cuda:10.2-runtime-ubuntu18.04" \
		.
fi
echo "Finished building $IMAGE_NAME"
